import { Head, Link, useForm } from '@inertiajs/react';
import type { FormEvent } from 'react';

type Debt = { key: string; source_type: string; source_id: number; description: string; purchased_at: string; amount_cents: number; applied_cents: number };
type Props = { receipt: { id: number; participant: { name: string }; received_at: string; amount_cents: number }; debts: Debt[] };

export default function ReceiptApplications({ receipt, debts }: Props) {
    const form = useForm({ applications: debts.map((debt) => ({ source_type: debt.source_type, source_id: debt.source_id, amount: debt.applied_cents > 0 ? (debt.applied_cents / 100).toFixed(2) : '' })) });
    const submit = (event: FormEvent) => { event.preventDefault(); form.transform((data) => ({ applications: data.applications.filter((application) => Number(application.amount.replace(',', '.')) > 0) })); form.put(`/receipts/${receipt.id}/applications`, { onSuccess: () => form.reset() }); };
    const setAmount = (index: number, amount: string) => form.setData('applications', form.data.applications.map((application, applicationIndex) => applicationIndex === index ? { ...application, amount } : application));
    return <><Head title="Ajustar recebimento" /><main className="min-h-screen bg-slate-950 px-5 py-6 text-white sm:px-8 lg:px-12 lg:py-10"><div className="mx-auto max-w-3xl"><Link href="/balances" className="text-sm text-emerald-300">← Voltar para saldos</Link><header className="mt-6"><p className="text-sm font-medium text-emerald-300">Recebimento de {receipt.participant.name}</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Ajustar aplicações</h1><p className="mt-2 text-sm text-slate-400">Valor recebido: {formatMoney(receipt.amount_cents)} em {formatDate(receipt.received_at)}. Use “Excluir aplicação” para desvincular um lançamento; a alteração será confirmada ao salvar.</p></header><form onSubmit={submit} className="mt-8 rounded-3xl border border-white/10 bg-slate-900/70 p-6"><div className="space-y-3">{debts.length === 0 && <p className="rounded-xl border border-dashed border-white/10 px-4 py-6 text-center text-sm text-slate-500">Nenhum saldo disponível para esta pessoa.</p>}{debts.map((debt, index) => <label key={debt.key} className="flex flex-col gap-3 rounded-2xl border border-white/5 bg-white/[0.03] p-4 sm:flex-row sm:items-center sm:justify-between"><span><span className="block text-sm text-slate-200">{debt.description}</span><span className="mt-1 block text-xs text-slate-500">{formatDate(debt.purchased_at)} · devido {formatMoney(debt.amount_cents)}</span></span><span className="flex w-full items-center gap-2 sm:w-auto"><input aria-label={`Aplicação para ${debt.description}`} inputMode="decimal" placeholder="0,00" value={form.data.applications[index]?.amount ?? ''} onChange={(event) => setAmount(index, event.target.value)} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-white sm:w-32" />{form.data.applications[index]?.amount && <button type="button" onClick={() => setAmount(index, '')} className="shrink-0 text-xs font-semibold text-rose-300">Excluir aplicação</button>}</span></label>)}</div>{form.errors.applications && <p className="mt-3 text-sm text-rose-300">{form.errors.applications}</p>}<div className="mt-6 flex justify-end gap-3"><Link href="/balances" className="rounded-xl px-4 py-2.5 text-sm text-slate-400">Cancelar</Link><button disabled={form.processing} className="rounded-xl bg-emerald-400 px-5 py-2.5 text-sm font-bold text-slate-950">Salvar aplicações</button></div></form></div></main></>;
}

function formatMoney(cents: number): string { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(cents / 100); }
function formatDate(value: string): string { return new Intl.DateTimeFormat('pt-BR').format(new Date(`${value}T12:00:00`)); }
