import { FormEvent } from 'react';
import { Head, Link, useForm } from '@inertiajs/react';

type ImportData = { id: number; original_filename: string };
type Row = { id: number; row_number: number; raw_data: Record<string, string>; status: string };
type Props = { import: ImportData; headers: string[]; rows: Row[]; mapping: Record<string, string | null> };
const fields = [{ key: 'purchased_at', label: 'Data' }, { key: 'description', label: 'Descrição interna' }, { key: 'card_name', label: 'Nome no cartão/fatura' }, { key: 'amount', label: 'Valor' }, { key: 'payer', label: 'Pagador' }, { key: 'participant', label: 'Participante' }, { key: 'payment_method', label: 'Forma de pagamento' }, { key: 'category', label: 'Categoria' }, { key: 'origin', label: 'Origem' }];
const selectClass = 'w-full rounded-xl border border-white/10 bg-slate-800 px-3 py-2.5 text-sm text-white outline-none focus:border-emerald-300';

export default function Mapping({ import: importData, headers, rows, mapping }: Props) {
    const form = useForm({ mapping, period_start: '', period_end: '' });
    const submit = (event: FormEvent) => { event.preventDefault(); form.post(`/imports/${importData.id}/mapping`); };

    return <><Head title="Mapear importação" /><main className="min-h-screen bg-slate-950 px-5 py-6 text-white sm:px-8 lg:px-12 lg:py-10"><div className="mx-auto max-w-6xl"><Link href="/imports/create" className="text-sm text-emerald-300">← Escolher outro arquivo</Link><header className="mt-8"><p className="text-sm font-medium text-emerald-300">Prévia · {importData.original_filename}</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Mapeie as colunas</h1><p className="mt-2 text-sm text-slate-400">Escolha qual coluna representa cada conceito. Nenhuma linha será importada nesta etapa.</p></header><form onSubmit={submit} className="mt-8 space-y-5"><section className="rounded-3xl border border-white/10 bg-slate-900/70 p-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{fields.map((field) => <label key={field.key}><span className="mb-2 block text-sm font-medium text-slate-300">{field.label}</span><select value={form.data.mapping[field.key] ?? ''} onChange={(event) => form.setData('mapping', { ...form.data.mapping, [field.key]: event.target.value || null })} className={selectClass}><option value="">Não mapeado</option>{headers.map((header) => <option key={header} value={header}>{header}</option>)}</select></label>)}</div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-medium text-slate-300">Período esperado (início)</span><input type="date" value={form.data.period_start} onChange={(event) => form.setData('period_start', event.target.value)} className={selectClass} /></label><label><span className="mb-2 block text-sm font-medium text-slate-300">Período esperado (fim)</span><input type="date" value={form.data.period_end} onChange={(event) => form.setData('period_end', event.target.value)} className={selectClass} /></label></div></section><section className="rounded-3xl border border-white/10 bg-slate-900/70 p-6"><h2 className="font-semibold">Primeiras linhas</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-3 py-3">Linha</th>{headers.map((header) => <th key={header} className="px-3 py-3">{header}</th>)}</tr></thead><tbody className="divide-y divide-white/5">{rows.map((row) => <tr key={row.id}><td className="px-3 py-3 text-slate-500">{row.row_number}</td>{headers.map((header) => <td key={header} className="max-w-56 truncate px-3 py-3 text-slate-300">{row.raw_data[header] || '—'}</td>)}</tr>)}</tbody></table></div></section><div className="flex justify-end gap-3"><Link href="/imports/create" className="rounded-xl px-4 py-2.5 text-sm text-slate-400">Cancelar</Link><button disabled={form.processing} className="rounded-xl bg-emerald-400 px-5 py-2.5 text-sm font-bold text-slate-950">{form.processing ? 'Validando...' : 'Validar e revisar'}</button></div></form></div></main></>;
}
