import { Head, Link, useForm } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

type Option = { id: number; name: string; is_default?: boolean };
type Allocation = { id?: number; participant_id: number; amount_cents: number; percentage_basis_points: number | null; participant?: Option | null };
type Purchase = { id: number; description: string; amount_cents: number; allocation_mode: string | null; allocations: Allocation[] };
type Row = { participant_id: string; amount: string; percentage: string };
type Props = { purchase: Purchase; participants: Option[]; flash?: { success?: string } };
const inputClass = 'w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2.5 text-sm text-white outline-none placeholder:text-slate-500 focus:border-emerald-300';
const selectClass = 'w-full rounded-xl border border-white/10 bg-slate-800 px-3 py-2.5 text-sm text-white outline-none focus:border-emerald-300 [&>option]:bg-slate-800 [&>option]:text-white';

export default function Allocations({ purchase, participants, flash }: Props) {
    const [mode, setMode] = useState(purchase.allocation_mode ?? 'equal');
    const selfId = participants.find((participant) => participant.is_default)?.id.toString() ?? '';
    const initialRows = purchase.allocations.length > 0 ? purchase.allocations.map((allocation) => ({ participant_id: allocation.participant_id.toString(), amount: allocation.amount_cents ? (allocation.amount_cents / 100).toFixed(2) : '', percentage: allocation.percentage_basis_points ? (allocation.percentage_basis_points / 100).toFixed(2) : '' })) : [{ participant_id: selfId, amount: '', percentage: '' }];
    const form = useForm<{ allocation_mode: string; allocations: Row[] }>({ allocation_mode: mode, allocations: initialRows });
    const addRow = () => form.setData('allocations', [...form.data.allocations, { participant_id: selfId, amount: '', percentage: '' }]);
    const updateRow = (index: number, key: keyof Row, value: string) => form.setData('allocations', form.data.allocations.map((row, rowIndex) => rowIndex === index ? { ...row, [key]: value } : row));
    const submit = (event: FormEvent) => { event.preventDefault(); form.setData('allocation_mode', mode); form.put(`/purchases/${purchase.id}/allocations`); };
    return <><Head title="Divisão da compra" /><main className="min-h-screen bg-slate-950 px-5 py-6 text-white sm:px-8 lg:px-12 lg:py-10"><div className="mx-auto max-w-3xl"><Link href={`/purchases/${purchase.id}/edit`} className="text-sm text-emerald-300">← Voltar para a compra</Link><header className="mt-6"><p className="text-sm font-medium text-emerald-300">Divisão</p><h1 className="mt-1 text-3xl font-bold tracking-tight">{purchase.description}</h1><p className="mt-2 text-sm text-slate-400">Valor total: <strong className="text-white">{formatMoney(purchase.amount_cents)}</strong>. O pagador continua separado dos participantes.</p></header>{flash?.success && <p role="status" className="mt-5 rounded-xl border border-emerald-300/20 bg-emerald-300/10 px-4 py-3 text-sm text-emerald-200">{flash.success}</p>}<form onSubmit={submit} className="mt-8 rounded-3xl border border-white/10 bg-slate-900/70 p-6"><label className="block"><span className="mb-2 block text-sm font-medium text-slate-300">Modo de divisão</span><select value={mode} onChange={(event) => { setMode(event.target.value); form.setData('allocation_mode', event.target.value); }} className={selectClass}><option value="equal">Partes iguais</option><option value="amount">Valores definidos</option><option value="percentage">Percentuais</option></select></label><div className="mt-5 space-y-3">{form.data.allocations.map((row, index) => <div key={index} className="grid gap-3 rounded-2xl border border-white/5 bg-white/[0.03] p-3 sm:grid-cols-[1fr_9rem]"><select required value={row.participant_id} onChange={(event) => updateRow(index, 'participant_id', event.target.value)} className={selectClass}>{participants.map((participant) => <option key={participant.id} value={participant.id}>{participant.name}</option>)}</select>{mode === 'amount' && <input value={row.amount} onChange={(event) => updateRow(index, 'amount', event.target.value)} placeholder="Valor" inputMode="decimal" className={inputClass} />}{mode === 'percentage' && <input value={row.percentage} onChange={(event) => updateRow(index, 'percentage', event.target.value)} placeholder="%" inputMode="decimal" className={inputClass} />}</div>)}</div>{form.errors.allocations && <p className="mt-3 text-sm text-rose-300">{form.errors.allocations}</p>}<button type="button" onClick={addRow} className="mt-4 rounded-xl border border-emerald-300/30 px-4 py-2.5 text-sm font-semibold text-emerald-300">＋ Adicionar participante</button><div className="mt-6 flex justify-end gap-3"><Link href="/" className="rounded-xl px-4 py-2.5 text-sm text-slate-400">Cancelar</Link><button disabled={form.processing} className="rounded-xl bg-emerald-400 px-5 py-2.5 text-sm font-bold text-slate-950">Salvar divisão</button></div></form></div></main></>;
}

function formatMoney(cents: number): string { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(cents / 100); }
