import { Form, Head, Link, useForm } from '@inertiajs/react';

type Option = { id: number; name: string };
type Purchase = { id: number; purchased_at: string; description: string; amount_cents: number; payer_id: number | null; participant_id: number | null; payment_method_id: number | null; category_id: number | null };
type Props = { purchase: Purchase | null; participants: Option[]; categories: Option[]; paymentMethods: Option[] };
const inputClass = 'w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2.5 text-sm text-white outline-none placeholder:text-slate-500 focus:border-emerald-300';

export default function PurchaseForm({ purchase, participants, categories, paymentMethods }: Props) {
    const form = useForm({ purchased_at: purchase?.purchased_at?.slice(0, 10) ?? new Date().toISOString().slice(0, 10), description: purchase?.description ?? '', amount: purchase ? (purchase.amount_cents / 100).toFixed(2) : '', payer_id: purchase?.payer_id?.toString() ?? '', participant_id: purchase?.participant_id?.toString() ?? '', payment_method_id: purchase?.payment_method_id?.toString() ?? '', category_id: purchase?.category_id?.toString() ?? '' });
    const action = purchase ? `/purchases/${purchase.id}` : '/purchases';
    const submit = (event: React.FormEvent) => { event.preventDefault(); purchase ? form.patch(action) : form.post(action); };
    return <><Head title={purchase ? 'Editar compra' : 'Nova compra'} /><main className="min-h-screen bg-slate-950 px-5 py-6 text-white sm:px-8 lg:px-12 lg:py-10"><div className="mx-auto max-w-3xl"><Link href="/" className="text-sm text-emerald-300">← Voltar para visão geral</Link><header className="mt-6"><p className="text-sm font-medium text-emerald-300">Compras</p><h1 className="mt-1 text-3xl font-bold tracking-tight">{purchase ? 'Editar compra' : 'Nova compra'}</h1><p className="mt-2 text-sm text-slate-400">Registre os dados essenciais agora; os rateios detalhados entram no próximo fluxo.</p></header><form onSubmit={submit} className="mt-8 rounded-3xl border border-white/10 bg-slate-900/70 p-6"><div className="grid gap-5 sm:grid-cols-2"><Field label="Data"><input type="date" value={form.data.purchased_at} onChange={(event) => form.setData('purchased_at', event.target.value)} className={inputClass} />{form.errors.purchased_at && <Error text={form.errors.purchased_at} />}</Field><Field label="Valor total"><input inputMode="decimal" placeholder="0,00" value={form.data.amount} onChange={(event) => form.setData('amount', event.target.value)} className={inputClass} />{form.errors.amount && <Error text={form.errors.amount} />}</Field><Field label="Descrição" wide><input required maxLength={160} placeholder="Ex.: Mercado do mês" value={form.data.description} onChange={(event) => form.setData('description', event.target.value)} className={inputClass} />{form.errors.description && <Error text={form.errors.description} />}</Field><Field label="Pagador"><Select value={form.data.payer_id} onChange={(value) => form.setData('payer_id', value)} options={participants} placeholder="Selecione o pagador" />{form.errors.payer_id && <Error text={form.errors.payer_id} />}</Field><Field label="Participante"><Select value={form.data.participant_id} onChange={(value) => form.setData('participant_id', value)} options={participants} placeholder="Selecione o participante" />{form.errors.participant_id && <Error text={form.errors.participant_id} />}</Field><Field label="Forma de pagamento"><Select value={form.data.payment_method_id} onChange={(value) => form.setData('payment_method_id', value)} options={paymentMethods} placeholder="Selecione a forma" />{form.errors.payment_method_id && <Error text={form.errors.payment_method_id} />}</Field><Field label="Categoria"><Select value={form.data.category_id} onChange={(value) => form.setData('category_id', value)} options={categories} placeholder="Selecione a categoria" />{form.errors.category_id && <Error text={form.errors.category_id} />}</Field></div><div className="mt-6 flex justify-end gap-3"><Link href="/" className="rounded-xl px-4 py-2.5 text-sm text-slate-400">Cancelar</Link><button disabled={form.processing} className="rounded-xl bg-emerald-400 px-5 py-2.5 text-sm font-bold text-slate-950">{purchase ? 'Salvar alterações' : 'Registrar compra'}</button></div></form></div></main></>;
}

function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) { return <label className={wide ? 'sm:col-span-2' : ''}><span className="mb-2 block text-sm font-medium text-slate-300">{label}</span>{children}</label>; }
function Select({ value, onChange, options, placeholder }: { value: string; onChange: (value: string) => void; options: Option[]; placeholder: string }) { return <select required value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-xl border border-white/10 bg-slate-800 px-3 py-2.5 text-sm text-white outline-none focus:border-emerald-300 [&>option]:bg-slate-800 [&>option]:text-white"><option value="">{placeholder}</option>{options.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select>; }
function Error({ text }: { text: string }) { return <p className="mt-1 text-xs text-rose-300">{text}</p>; }
