<?php

use App\Http\Controllers\AnalysisController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\BackupController;
use App\Http\Controllers\BalanceController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ExportController;
use App\Http\Controllers\InstallmentController;
use App\Http\Controllers\InstallmentOccurrenceController;
use App\Http\Controllers\OpenAiController;
use App\Http\Controllers\ParticipantController;
use App\Http\Controllers\PaymentMethodController;
use App\Http\Controllers\PurchaseAllocationController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\ReceiptController;
use App\Http\Controllers\RecurrenceController;
use App\Http\Controllers\RecurrenceOccurrenceController;
use App\Http\Controllers\SalaryController;
use App\Http\Controllers\SpreadsheetImportController;
use Illuminate\Support\Facades\Route;

Route::get('/', DashboardController::class)->name('dashboard');
Route::get('/analysis', AnalysisController::class)->name('analysis');
Route::get('/exports', [ExportController::class, 'index'])->name('exports.index');
Route::get('/exports/csv/{type}', [ExportController::class, 'csv'])->name('exports.csv');
Route::get('/exports/excel', [ExportController::class, 'excel'])->name('exports.excel');
Route::get('/exports/markdown', [ExportController::class, 'markdown'])->name('exports.markdown');
Route::get('/exports/prompt', [ExportController::class, 'prompt'])->name('exports.prompt');
Route::post('/openai/responses', OpenAiController::class)->name('openai.responses.store');
Route::get('/history', [AuditLogController::class, 'index'])->name('history');
Route::get('/settings/backups', [BackupController::class, 'index'])->name('settings.backups');
Route::patch('/settings/backups', [BackupController::class, 'update'])->name('settings.backups.update');
Route::post('/settings/backups', [BackupController::class, 'store'])->name('settings.backups.store');
Route::post('/settings/backups/restore', [BackupController::class, 'restore'])->name('settings.backups.restore');
Route::get('/imports/create', [SpreadsheetImportController::class, 'create'])->name('imports.create');
Route::post('/imports', [SpreadsheetImportController::class, 'store'])->name('imports.store');
Route::get('/imports/{import}/mapping', [SpreadsheetImportController::class, 'mapping'])->name('imports.mapping');
Route::post('/imports/{import}/mapping', [SpreadsheetImportController::class, 'map'])->name('imports.map');
Route::get('/imports/{import}/review', [SpreadsheetImportController::class, 'review'])->name('imports.review');
Route::patch('/imports/{import}/rows/{row}', [SpreadsheetImportController::class, 'updateRow'])->name('imports.rows.update');
Route::post('/imports/{import}/confirm', [SpreadsheetImportController::class, 'confirm'])->name('imports.confirm');
Route::patch('/settings/salary', [SalaryController::class, 'update'])->name('settings.salary.update');
Route::get('/balances', BalanceController::class)->name('balances');
Route::get('/receipts/create', [ReceiptController::class, 'create'])->name('receipts.create');
Route::post('/receipts', [ReceiptController::class, 'store'])->name('receipts.store');
Route::get('/receipts/{receipt}/edit', [ReceiptController::class, 'edit'])->name('receipts.edit');
Route::put('/receipts/{receipt}/applications', [ReceiptController::class, 'updateApplications'])->name('receipts.applications.update');

Route::get('/purchases/create', [PurchaseController::class, 'create'])->name('purchases.create');
Route::get('/purchases/create/simple', [PurchaseController::class, 'createSimple'])->name('purchases.create.simple');
Route::post('/purchases', [PurchaseController::class, 'store'])->name('purchases.store');
Route::get('/purchases/{purchase}/edit', [PurchaseController::class, 'edit'])->name('purchases.edit');
Route::patch('/purchases/{purchase}', [PurchaseController::class, 'update'])->name('purchases.update');
Route::delete('/purchases/{purchase}', [PurchaseController::class, 'destroy'])->name('purchases.destroy');
Route::patch('/purchases/{purchase}/archive', [PurchaseController::class, 'archive'])->name('purchases.archive');
Route::patch('/purchases/{purchase}/restore', [PurchaseController::class, 'restore'])->name('purchases.restore');
Route::get('/purchases/{purchase}/allocations/edit', [PurchaseAllocationController::class, 'edit'])->name('purchases.allocations.edit');
Route::put('/purchases/{purchase}/allocations', [PurchaseAllocationController::class, 'update'])->name('purchases.allocations.update');

Route::get('/installments', [InstallmentController::class, 'index'])->name('installments.index');
Route::get('/installments/create', [InstallmentController::class, 'create'])->name('installments.create');
Route::post('/installments', [InstallmentController::class, 'store'])->name('installments.store');
Route::patch('/installments/{installment}/archive', [InstallmentController::class, 'archive'])->name('installments.archive');
Route::get('/installment-occurrences/{installmentOccurrence}/edit', [InstallmentOccurrenceController::class, 'edit'])->name('installment-occurrences.edit');
Route::patch('/installment-occurrences/{installmentOccurrence}', [InstallmentOccurrenceController::class, 'update'])->name('installment-occurrences.update');
Route::get('/recurrences', [RecurrenceController::class, 'index'])->name('recurrences.index');
Route::get('/recurrences/create', [RecurrenceController::class, 'create'])->name('recurrences.create');
Route::post('/recurrences', [RecurrenceController::class, 'store'])->name('recurrences.store');
Route::get('/recurrences/{recurrence}/edit', [RecurrenceController::class, 'edit'])->name('recurrences.edit');
Route::patch('/recurrences/{recurrence}', [RecurrenceController::class, 'update'])->name('recurrences.update');
Route::patch('/recurrences/{recurrence}/activate', [RecurrenceController::class, 'activate'])->name('recurrences.activate');
Route::patch('/recurrences/{recurrence}/deactivate', [RecurrenceController::class, 'deactivate'])->name('recurrences.deactivate');
Route::get('/recurrence-occurrences/{recurrenceOccurrence}/edit', [RecurrenceOccurrenceController::class, 'edit'])->name('recurrence-occurrences.edit');
Route::patch('/recurrence-occurrences/{recurrenceOccurrence}', [RecurrenceOccurrenceController::class, 'update'])->name('recurrence-occurrences.update');

Route::get('/settings/catalogs', [ParticipantController::class, 'index'])->name('settings.catalogs');
Route::post('/participants', [ParticipantController::class, 'store'])->name('participants.store');
Route::patch('/participants/{participant}', [ParticipantController::class, 'update'])->name('participants.update');
Route::delete('/participants/{participant}', [ParticipantController::class, 'destroy'])->name('participants.destroy');
Route::post('/categories', [CategoryController::class, 'store'])->name('categories.store');
Route::patch('/categories/{category}', [CategoryController::class, 'update'])->name('categories.update');
Route::delete('/categories/{category}', [CategoryController::class, 'destroy'])->name('categories.destroy');
Route::post('/payment-methods', [PaymentMethodController::class, 'store'])->name('payment-methods.store');
Route::patch('/payment-methods/{payment_method}', [PaymentMethodController::class, 'update'])->name('payment-methods.update');
Route::delete('/payment-methods/{payment_method}', [PaymentMethodController::class, 'destroy'])->name('payment-methods.destroy');
