import { Form, Head, Link } from '@inertiajs/react';

type Occurrence = { id: number; number: number; purchasedAt: string; amountCents: number; isAdjusted: boolean; archivedAt: string | null };
type Installment = { id: number; startDate: string; description: string; cardName: string | null; totalCents: number; installmentCount: number; payer: string | null; participant: string | null; paymentMethod: string | null; category: string | null; archivedAt: string | null; occurrences: Occurrence[] };
type Props = { installments: Installment[]; flash?: { success?: string } };

export default function InstallmentsIndex({ installments, flash }: Props) {
    return <><Head title="Parcelamentos" /><main className="min-h-screen bg-slate-950 px-5 py-6 text-white sm:px-8 lg:px-12 lg:py-10"><div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-center justify-between gap-3"><Link href="/" className="text-sm text-emerald-300">← Voltar para visão geral</Link><Link href="/purchases/create" className="rounded-xl border border-emerald-300/30 px-4 py-2.5 text-sm font-semibold text-emerald-300">＋ Nova compra</Link></div><header className="mt-6"><p className="text-sm font-medium text-emerald-300">Planejamento</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Parcelamentos</h1><p className="mt-2 text-sm text-slate-400">Consulte as parcelas cadastradas e os ajustes feitos em ocorrências específicas.</p></header>{flash?.success && <p role="status" className="mt-5 rounded-xl border border-emerald-300/20 bg-emerald-300/10 px-4 py-3 text-sm text-emerald-200">{flash.success}</p>}<section className="mt-8 space-y-4">{installments.length === 0 && <div className="rounded-3xl border border-dashed border-white/10 px-5 py-16 text-center"><p className="text-sm text-slate-400">Nenhum parcelamento cadastrado.</p><p className="mt-2 text-xs text-slate-500">Use o botão Nova compra na tela inicial para cadastrar um parcelamento.</p></div>}{installments.map((installment) => <InstallmentCard key={installment.id} installment={installment} />)}</section></div></main></>;
}

function InstallmentCard({ installment }: { installment: Installment }) {
    const activeOccurrences = installment.occurrences.filter((occurrence) => occurrence.archivedAt === null);
    return <article className={`rounded-3xl border bg-slate-900/70 p-6 ${installment.archivedAt ? 'border-white/5 opacity-70' : 'border-white/10'}`}><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-white">{installment.description}</h2>{installment.archivedAt && <span className="rounded-full bg-slate-700 px-2 py-1 text-xs text-slate-400">Encerrado</span>}</div><p className="mt-1 text-sm text-slate-400">{installment.paymentMethod ?? 'Sem forma'} · início em {formatDate(installment.startDate)} · {installment.participant ?? 'Eu'}</p><p className="mt-1 text-xs text-slate-500">{installment.cardName ? `Fatura: ${installment.cardName} · ` : ''}{installment.installmentCount} parcelas · total {formatMoney(installment.totalCents)}</p></div>{!installment.archivedAt && <Form action={`/installments/${installment.id}/archive`} method="patch" onBefore={() => window.confirm(`Encerrar ${installment.description}? As parcelas passadas serão preservadas.`)}><button className="text-xs font-semibold text-amber-300">Encerrar</button></Form>}</div><div className="mt-5 grid gap-2 sm:grid-cols-2">{installment.occurrences.map((occurrence) => <div key={occurrence.id} className={`flex items-center justify-between rounded-xl border px-3 py-2.5 ${occurrence.archivedAt ? 'border-white/5 bg-white/[0.01] text-slate-600' : 'border-white/5 bg-white/[0.03]'}`}><div><p className="text-sm text-slate-200">Parcela {occurrence.number}/{installment.installmentCount}</p><p className="text-xs text-slate-500">{formatDate(occurrence.purchasedAt)}{occurrence.isAdjusted ? ' · ajustada' : ''}</p></div><div className="flex items-center gap-3"><strong className="text-sm text-white">{formatMoney(occurrence.amountCents)}</strong>{occurrence.archivedAt === null && <Link href={`/installment-occurrences/${occurrence.id}/edit`} className="text-xs font-semibold text-emerald-300">{occurrence.number === 1 ? 'Ajustar cronograma' : 'Ajustar parcela'}</Link>}</div></div>)}</div><p className="mt-4 text-xs text-slate-500">{activeOccurrences.length} parcela(s) ativa(s) visível(is) no calendário.</p></article>;
}

function formatMoney(cents: number): string { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(cents / 100); }
function formatDate(value: string): string { return new Intl.DateTimeFormat('pt-BR').format(new Date(`${value}T12:00:00`)); }
