import { Form, Head, Link } from '@inertiajs/react';

type Occurrence = { id: number; purchasedAt: string; amountCents: number; isAdjusted: boolean; archivedAt: string | null };
type Recurrence = { id: number; startDate: string; endDate: string | null; dayOfMonth: number; description: string; cardName: string | null; amountCents: number; payer: string | null; participant: string | null; paymentMethod: string | null; category: string | null; active: boolean; occurrences: Occurrence[] };
type Props = { recurrences: Recurrence[]; flash?: { success?: string } };

export default function RecurrencesIndex({ recurrences, flash }: Props) {
    return <><Head title="Compras recorrentes" /><main className="min-h-screen bg-slate-950 px-5 py-6 text-white sm:px-8 lg:px-12 lg:py-10"><div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-center justify-between gap-3"><Link href="/" className="text-sm text-emerald-300">← Voltar para visão geral</Link><Link href="/purchases/create" className="rounded-xl border border-emerald-300/30 px-4 py-2.5 text-sm font-semibold text-emerald-300">＋ Nova compra</Link></div><header className="mt-6"><p className="text-sm font-medium text-emerald-300">Planejamento</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Compras recorrentes</h1><p className="mt-2 text-sm text-slate-400">Regras mensais e suas próximas ocorrências, sem misturar com compras simples.</p></header>{flash?.success && <p role="status" className="mt-5 rounded-xl border border-emerald-300/20 bg-emerald-300/10 px-4 py-3 text-sm text-emerald-200">{flash.success}</p>}<section className="mt-8 space-y-4">{recurrences.length === 0 && <div className="rounded-3xl border border-dashed border-white/10 px-5 py-16 text-center"><p className="text-sm text-slate-400">Nenhuma compra recorrente cadastrada.</p><p className="mt-2 text-xs text-slate-500">Use o botão Nova compra na tela inicial para cadastrar uma regra.</p></div>}{recurrences.map((recurrence) => <RecurrenceCard key={recurrence.id} recurrence={recurrence} />)}</section></div></main></>;
}

function RecurrenceCard({ recurrence }: { recurrence: Recurrence }) {
    const visibleOccurrences = recurrence.occurrences.filter((occurrence) => occurrence.archivedAt === null);
    return <article className={`rounded-3xl border bg-slate-900/70 p-6 ${recurrence.active ? 'border-white/10' : 'border-white/5 opacity-70'}`}><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-white">{recurrence.description}</h2><span className={`rounded-full px-2 py-1 text-xs ${recurrence.active ? 'bg-emerald-300/10 text-emerald-300' : 'bg-slate-700 text-slate-400'}`}>{recurrence.active ? 'Ativa' : 'Desativada'}</span></div><p className="mt-1 text-sm text-slate-400">{recurrence.paymentMethod ?? 'Sem forma'} · dia {recurrence.dayOfMonth} · {recurrence.participant ?? 'Eu'}</p><p className="mt-1 text-xs text-slate-500">{recurrence.cardName ? `Fatura: ${recurrence.cardName} · ` : ''}{formatMoney(recurrence.amountCents)} por mês · {recurrence.endDate ? `até ${formatDate(recurrence.endDate)}` : 'sem data final'}</p></div><div className="flex items-center gap-3"><Link href={`/recurrences/${recurrence.id}/edit`} className="text-xs font-semibold text-emerald-300">Editar regra</Link>{recurrence.active ? <Form action={`/recurrences/${recurrence.id}/deactivate`} method="patch"><button className="text-xs font-semibold text-amber-300">Desativar</button></Form> : <Form action={`/recurrences/${recurrence.id}/activate`} method="patch"><button className="text-xs font-semibold text-emerald-300">Ativar</button></Form>}</div></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{visibleOccurrences.map((occurrence) => <div key={occurrence.id} className="flex items-center justify-between rounded-xl border border-white/5 bg-white/[0.03] px-3 py-2.5"><div><p className="text-sm text-slate-200">{formatDate(occurrence.purchasedAt)}{occurrence.isAdjusted ? ' · ajustada' : ''}</p><p className="text-xs text-slate-500">Ocorrência da regra</p></div><div className="flex items-center gap-3"><strong className="text-sm text-white">{formatMoney(occurrence.amountCents)}</strong><Link href={`/recurrence-occurrences/${occurrence.id}/edit`} className="text-xs font-semibold text-emerald-300">Ajustar</Link></div></div>)}</div><p className="mt-4 text-xs text-slate-500">{visibleOccurrences.length} ocorrência(s) carregada(s).</p></article>;
}

function formatMoney(cents: number): string { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(cents / 100); }
function formatDate(value: string): string { return new Intl.DateTimeFormat('pt-BR').format(new Date(`${value}T12:00:00`)); }
